namespace Imoveis.Application.Contracts.Legacy;

public sealed record LegacyImportRequest(
    IReadOnlyList<LegacyEstateRecord> Estates,
    IReadOnlyList<LegacyFinancialRecord> FinancialRecords,
    IReadOnlyList<LegacyHistoryRecord> Histories,
    IReadOnlyList<LegacyPendencyAcronymRecord> PendencyAcronyms,
    IReadOnlyList<LegacyPendencyStateRecord> PendencyStates);

public sealed record LegacyEstateRecord(
    int Id,
    string? Nickname,
    string? Type,
    string? Address,
    string? Status,
    int? PaymentDay,
    string? PaymentLocation,
    int? NumOfRooms,
    bool? CleaningIncluded,
    bool? Elevator,
    bool? Garage,
    string? ContractWith,
    DateOnly? StartDate,
    DateOnly? EndDate,
    string? ReadjustmentIndex,
    string? Administrator,
    string? AdministratorPhone,
    string? AdministratorEmail,
    string? AdministrateTax,
    string? Lessee,
    string? LesseePhone,
    string? OptionalContactName,
    string? OptionalContactNumber,
    string? Guarantor,
    string? GuarantorData,
    string? GuarantorNumber,
    decimal? Condominium,
    string? IPTU,
    string? Observation,
    string? Registration,
    string? Scripture,
    string? RegistrationCertification,
    decimal? TaxIPTU,
    decimal? RentValue,
    decimal? Gas,
    decimal? Light,
    decimal? Water,
    string? GasInformation,
    string? LightInformation,
    string? WaterInformation,
    string? ContractRegistration,
    string? Insurance,
    string? SignatureRecognition,
    string? Lawyer,
    string? LawyerData,
    string? BeforePhoto,
    string? AfterPhoto,
    string? Proprietary,
    DateOnly? Unoccupied);

public sealed record LegacyFinancialRecord(
    int EstateId,
    int Year,
    int Month,
    DateOnly? PropertyTaxIPTU,
    decimal? PropertyTaxIPTUValue,
    string? StatusPropertyTaxIPTU,
    string? PropertyTaxIPTUPerson,
    DateOnly? Rent,
    decimal? RentValue,
    string? StatusRent,
    string? RentPerson,
    DateOnly? Condominium,
    decimal? CondominiumValue,
    string? StatusCondominium,
    string? CondominiumPerson,
    DateOnly? Sabesp,
    decimal? SabespValue,
    string? StatusSabesp,
    string? SabespPerson,
    DateOnly? Enel,
    decimal? EnelValue,
    string? StatusEnel,
    string? EnelPerson,
    DateOnly? Gas,
    decimal? GasValue,
    string? StatusGas,
    string? GasPerson,
    DateOnly? Extra,
    decimal? ExtraValue,
    string? ExtraStatus,
    string? ExtraPerson,
    string? Observations);

public sealed record LegacyHistoryRecord(int EstateId, string? Data, DateTime? CreatedAtUtc);

public sealed record LegacyPendencyAcronymRecord(int Id, string Acronym, string? Description);

public sealed record LegacyPendencyStateRecord(int IdState, string PendencyAcronym, DateTime Date);

public sealed record LegacyImportResultDto(
    int ImportedProperties,
    int ImportedTenants,
    int ImportedLeases,
    int ImportedChargeTemplates,
    int ImportedExpenses,
    int ImportedHistoryEntries,
    int ImportedAttachments,
    int ImportedPendencies);
